// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmAkLjkgH3k3l5R1bgWw_FfJdZXIb2A0g',
    appId: '1:107263088141:web:9b9b6003cb212fec286744',
    messagingSenderId: '107263088141',
    projectId: 'test1-travelai',
    authDomain: 'test1-travelai.firebaseapp.com',
    storageBucket: 'test1-travelai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqjB49NpQlxfMDi_NySjnNnnH3abLhq8s',
    appId: '1:107263088141:android:297a53ad5e149fe5286744',
    messagingSenderId: '107263088141',
    projectId: 'test1-travelai',
    storageBucket: 'test1-travelai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCztgZvN62yzTn7fz6nbBP9RNidF4jmKho',
    appId: '1:582628433872:ios:f8de19a868643024a223d5',
    messagingSenderId: '582628433872',
    projectId: 'travel-ai-84a15',
    storageBucket: 'travel-ai-84a15.firebasestorage.app',
    iosBundleId: 'com.example.travelai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCztgZvN62yzTn7fz6nbBP9RNidF4jmKho',
    appId: '1:582628433872:ios:f8de19a868643024a223d5',
    messagingSenderId: '582628433872',
    projectId: 'travel-ai-84a15',
    storageBucket: 'travel-ai-84a15.firebasestorage.app',
    iosBundleId: 'com.example.travelai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmAkLjkgH3k3l5R1bgWw_FfJdZXIb2A0g',
    appId: '1:107263088141:web:1e684b30d883d950286744',
    messagingSenderId: '107263088141',
    projectId: 'test1-travelai',
    authDomain: 'test1-travelai.firebaseapp.com',
    storageBucket: 'test1-travelai.firebasestorage.app',
  );

}