import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

// Auto-generated by the FlutterFire CLI
import 'firebase_options.dart'; 

import 'src/routing/app_router.dart';
import 'src/theme/app_theme.dart';

void main() async {
  // Ensure Flutter bindings are initialized before calling native code
  WidgetsFlutterBinding.ensureInitialized();
  
  // Load environment variables (Gemini API Key)
  await dotenv.load(fileName: ".env");
  
  // Initialize Firebase with platform-specific options (Critical for Web)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Launch the app wrapped in Riverpod's ProviderScope for state management
  runApp(const ProviderScope(child: ExploristApp()));
}

class ExploristApp extends ConsumerWidget {
  const ExploristApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the router provider to handle navigation and auth redirects
    final router = ref.watch(routerProvider);
    
    return MaterialApp.router(
      title: 'Explorist AI',
      theme: AppTheme.lightTheme,
      routerConfig: router,
      debugShowCheckedModeBanner: false,
    );
  }
}