import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

// Auto-generated by the FlutterFire CLI
import 'firebase_options.dart'; 

import 'src/routing/app_router.dart';
import 'src/theme/app_theme.dart';

void main() async {
  // 1. Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Load Gemini API Key from .env file
  try {
    await dotenv.load(fileName: ".env");
  } catch (e) {
    debugPrint("Warning: .env file not found. Ensure GEMINI_API_KEY is set.");
  }
  
  // 3. Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // 4. Run App
  runApp(
    const ProviderScope(
      child: ExploristApp(),
    ),
  );
}

class ExploristApp extends ConsumerWidget {
  const ExploristApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // 5. Watch the routerProvider from app_router.dart
    final router = ref.watch(routerProvider);
    
    return MaterialApp.router(
      title: 'Explorist AI',
      // Uses the custom theme we discussed
      theme: AppTheme.lightTheme, 
      // Connects the GoRouter config
      routerConfig: router,
      debugShowCheckedModeBanner: false,
    );
  }
}